Fixes missing arguments in BankCommand
RoinujNosde/SimpleClans pull request #178
Opened 2021-04-29 08:50 UTC by Tomut0

Also updates messages.properties

2021-04-29 21:20 UTC, RoinujNosde requested changes

2021-04-29 21:20 UTC, RoinujNosde commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/ui/frames/staff/ClanDetailsFrame.java
> +        lore.add(lang("gui.clandetails.bank.balance.lore", getViewer(), clan.getBalance()));
Can use this instead:
```java
List<String> lore = Collections.singletonList(lang("gui.clandetails.bank.balance.lore", getViewer(), clan.getBalance()));
```

2021-04-29 21:20 UTC, RoinujNosde commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/ui/frames/staff/ClanDetailsFrame.java
> +        SCComponent bank = new SCComponentImpl(lang("gui.clandetails.bank.title", getViewer()), lore, XMaterial.GOLD_INGOT, 40);
"gui.clandetails.bank.balance.lore"
"gui.clandetails.bank.title"
Did you add those to the messages file?

2021-04-29 21:20 UTC, RoinujNosde commented on src/main/resources/messages.properties
> +command.description.fee.check=Checks the value of your clan's fee and if it''s enabled
clan''s

2021-04-30 00:36 UTC, Tomut0 commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/ui/frames/staff/ClanDetailsFrame.java
> +        SCComponent bank = new SCComponentImpl(lang("gui.clandetails.bank.title", getViewer()), lore, XMaterial.GOLD_INGOT, 40);
![изображение](https://user-images.githubusercontent.com/42711312/116634636-46d3aa80-a965-11eb-8f32-584a41e50c0c.png)

2021-04-30 01:22 UTC, RoinujNosde approved these changes

2021-04-30 01:23 UTC, merged