Cancel clan/rank creation
RoinujNosde/SimpleClans pull request #184
Opened 2021-05-01 07:12 UTC by Tomut0

2021-05-01 20:37 UTC, RoinujNosde requested changes

2021-05-01 20:37 UTC, RoinujNosde commented on src/main/resources/messages.properties
> +no=No
I think this should be "cancel"

2021-05-01 20:37 UTC, RoinujNosde commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/conversation/CreateRankNamePrompt.java
> +        if (input.equalsIgnoreCase(no)) {
In ConversationFactory there is a method withCancelWord (I think), so we don't need to check  that.

2021-05-02 04:28 UTC, Tomut0 commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/conversation/CreateRankNamePrompt.java
> +        if (input.equalsIgnoreCase(no)) {
Probably, you meant `withEscapeSequence()`
![изображение](https://user-images.githubusercontent.com/42711312/116802001-dc16a080-ab17-11eb-9545-86355335f19c.png)

2021-05-02 12:36 UTC, RoinujNosde requested changes

2021-05-02 12:36 UTC, RoinujNosde commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/conversation/RequestCanceller.java
> +            context.getForWhom().sendRawMessage(closedMessage);
Is this message sent?
If you are in a conversation, sendMessage() won't work.

2021-05-02 12:36 UTC, RoinujNosde commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/conversation/RequestCanceller.java
> +        if (closedMessage != null) {
And this will be true everytime.

2021-05-02 12:36 UTC, RoinujNosde commented on src/main/resources/messages.properties
> +cancel.no=No
I meant "yes" or "cancel".
So:
```properties
yes= yes
cancel= cancel
```

2021-05-02 12:36 UTC, RoinujNosde commented on src/main/resources/messages.properties
> +insert.clan.tag=&bInsert the clan tag (or cancel - {0}):
So this would need to be:
`&bInsert the clan tag (or "{0}"):`

2021-05-02 13:02 UTC, Tomut0 commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/conversation/RequestCanceller.java
> +            context.getForWhom().sendRawMessage(closedMessage);
Sure, but I'm in ConversationFactory. 👺 
![изображение](https://user-images.githubusercontent.com/42711312/116814086-ac8b8680-ab5f-11eb-94cb-06e123a3710d.png)

2021-05-02 13:41 UTC, RoinujNosde requested changes
Last changes

2021-05-02 13:41 UTC, RoinujNosde commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/conversation/RequestCanceller.java
> +        return input.equals(escapeSequence);
equalsIgnoreCase

2021-05-02 13:41 UTC, RoinujNosde commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/conversation/RequestCanceller.java
> +        context.getForWhom().sendRawMessage(closedMessage);
Shouldn't this be sent *only* if they typed the word to cancel? Without a check it will probably send for every prompt.

2021-05-02 13:41 UTC, RoinujNosde commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/conversation/RequestCanceller.java
> +        this.closedMessage = closedMessage;
cancelledMessage to match the class name

2021-05-02 17:12 UTC, RoinujNosde approved these changes

2021-05-02 17:19 UTC, merged