Colored "none" message
RoinujNosde/SimpleClans pull request #185
Opened 2021-05-03 19:43 UTC by Tomut0

2021-05-03 19:50 UTC, RoinujNosde requested changes

2021-05-03 19:50 UTC, RoinujNosde commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/Clan.java
> +    public String getAllyString(String sep, @Nullable CommandSender viewer) {
Breaking change

2021-05-03 19:52 UTC, Tomut0 commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/Clan.java
> +    public String getAllyString(String sep, @Nullable CommandSender viewer) {
> 
> 
> Breaking change

I knew what you will say that

2021-05-03 22:10 UTC, RoinujNosde approved these changes

2021-05-04 12:10 UTC, RoinujNosde commented
#19

2021-05-04 12:11 UTC, merged