Let's log bank transactions! 😃
RoinujNosde/SimpleClans pull request #190
Opened 2021-05-11 20:52 UTC by Tomut0

### This PR implements #123.
Logging all bank operations into a one (*but can be changed if needed*) CSV file in `/SimpleClans/logs/bank.csv`.
It also makes possible to **change file size** (by default, 100Mb) in plugin's configuration.
**Easy to add a new type of bank loggers** by implementing the same named interface.

### Compability?
It uses internal Java's logging library (JUL) and has not any affect on other plugins. 

⚠️ If your log will be overfilled, then it will clears and writes again. 
You could set `economy.bank-logger.size` to `0`  to make it unlimited!
⚠️ Still work in progress.
<hr>
Really appreciate to @RoinujNosde for his help with this PR. <br>
![изображение](https://user-images.githubusercontent.com/42711312/117883132-b6299280-b2b3-11eb-9fab-53b5330d024e.png)

2021-05-12 10:55 UTC, RoinujNosde requested changes

2021-05-12 10:55 UTC, RoinujNosde commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/storage/CSVBankLogger.java
> +            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd - HH:mm");
Class variable

2021-05-12 10:58 UTC, RoinujNosde requested changes

2021-05-12 10:58 UTC, RoinujNosde commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/storage/BankLogger.java
> +package net.sacredlabyrinth.phaed.simpleclans.storage;
logger package
what if a logger is console based? It's not storage then.

2021-05-12 16:02 UTC, RoinujNosde approved these changes

2021-05-12 16:03 UTC, merged

2021-07-11 16:54 UTC, TomLewis commented
Awesome!