Disband command requires confirmation
RoinujNosde/SimpleClans pull request #299
Opened 2022-03-01 18:58 UTC by Tomut0

This pull request adds confirmation to discord command in order not to accidentally disband your clan.
The only thing that worries me is: wouldn't confirmation annoy people? 🤔

2022-03-01 19:00 UTC, RoinujNosde commented
> wouldn't confirmation annoy people? 

No.

2022-03-01 19:15 UTC, RoinujNosde requested changes

2022-03-01 19:15 UTC, RoinujNosde commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/commands/clan/LeaderCommands.java
> +        new SCConversation(plugin, player, new DisbandPrompt()).begin();
Since there is a confirmation via command, the GUI one could be removed, or it will be annoying for users.

2022-03-01 19:15 UTC, RoinujNosde commented on pom.xml
> +                            <outputDirectory>${test.server}\plugins</outputDirectory>
env.TEST_SERVER

2022-03-01 19:15 UTC, RoinujNosde commented on pom.xml
> +        <test.server>D:\Paper-1.18.1\</test.server>
Remove this

2022-03-01 19:15 UTC, RoinujNosde commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/conversation/ConfirmationPrompt.java
> +    protected Prompt decline(ClanPlayer sender, Clan clan, String input) {
Both implementations are overriding this method (and confirm()), they could be abstract.

2022-03-02 00:09 UTC, RoinujNosde commented
One unresolved conversation left.

2022-03-02 08:47 UTC, Tomut0 commented
> One unresolved conversation left.

Just forgot to mark 😄

2022-03-02 13:36 UTC, RoinujNosde approved these changes

2022-03-02 14:03 UTC, merged