feat: add PlayerResetKdrEvent
RoinujNosde/SimpleClans pull request #370
Opened 2023-05-02 04:39 UTC by SrBedrock

2023-05-02 06:29 UTC, Tomut0 requested changes

2023-05-02 06:29 UTC, Tomut0 commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/commands/staff/StaffCommands.java
> +            }
The previous KDR command was clearing KDR from all clan players, even if they are offline.

2023-05-02 10:05 UTC, SrBedrock commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/commands/staff/StaffCommands.java
> +            }
@Tomut0 What is the best solution in this case?

2023-05-02 10:48 UTC, Tomut0 commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/commands/staff/StaffCommands.java
> +            }
> @Tomut0 What is the best solution in this case?

IMO, PlayerResetKdrEvent could have `clanplayer` in the constructor args instead of `player`.

2023-05-02 10:52 UTC, SrBedrock commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/commands/staff/StaffCommands.java
> +            }
got it!

2023-05-02 11:26 UTC, SrBedrock commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/commands/staff/StaffCommands.java
> +            }
@RoinujNosde any feedback?

2023-05-02 13:13 UTC, RoinujNosde commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/commands/staff/StaffCommands.java
> +            }
Nothing to add.

2023-05-03 08:19 UTC, Tomut0 approved these changes
Looks good to me, thanks! 😀

2023-05-03 09:16 UTC, merged