feat: add %simpleclans_has_rank% placeholder
RoinujNosde/SimpleClans pull request #379
Opened 2023-06-17 19:08 UTC by SrBedrock

2023-06-17 19:24 UTC, RoinujNosde requested changes

2023-06-17 19:24 UTC, RoinujNosde commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/ClanPlayer.java
> +            return r != null;
Inline this

2023-06-17 20:45 UTC, Tomut0 commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/ClanPlayer.java
>          return false;
`return clan != null ? clan.hasRank(getRankId()) : false`
or even shorter:
`return !getRankId().isEmpty();`

2023-06-17 20:50 UTC, Tomut0 commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/ClanPlayer.java
>          return false;
Second case doesn't take care of accidentual situations, 
where incorrect rank is set somehow, but I still prefer it over the first one.

2023-06-17 23:46 UTC, Tomut0 approved these changes

2023-06-19 20:10 UTC, RoinujNosde approved these changes

2023-06-19 21:01 UTC, merged